apiVersion: 1

datasources:
  - name: Influx
    type: influxdb
    access: proxy
    url: http://influx:8086
    jsonData:
      version: Flux
      organization: org
      defaultBucket: INVERNADERO
      tlsSkipVerify: true
    secureJsonData:
      token: token-secret
