version: "3.2"
services:
  broker:
    container_name: 'rabbit'
    image: rabbit_image
    restart: always 
    ports:
        - 1883:1883
        - 5672:5672
        - 15672:15672
    build: 
      context: .
      dockerfile: rabbitmq/Dockerfile
    networks:
      default:
        aliases:
          - rabbit
#........................ influx .....................
  database:
    container_name: influx
    image: influx_image
    restart: always 
    ports:
        - 8086:8086
    build: 
      context: .
      dockerfile: influx/Dockerfile
    env_file:
      - influx/setup.env
    networks:
      default:
        aliases:
          - influx

  telegraf:
      container_name: telegraf
      image: telegraf-image
      restart: always
      build:
        context: .
        dockerfile: telegra/Dockerfile
      volumes:
        - ./telegra/telegra.conf:/etc/telegraf/telegraf.conf
      depends_on:
        - database
